config/routes.rb
Frete::Application.routes.draw do
  root to: 'pages#index'
  get 'pages/index'
  get 'pages/more/:id' => 'pages#more', as: :freight_profile
  post 'pages/result', as: :page_result
  get 'pages/result'
  resources :carriers, :except => [:show]
  resources :freights, :except => [:show]

end

app/models/carrier.rb
class Carrier < ActiveRecord::Base
  attr_accessible :name, :address, :city_id, :zip_code, :site, :phone, :e_mail
  belongs_to :city
  has_one    :freight
  validates_presence_of  :name
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :name, :state
  validates :name, :state, :presence => true
  has_one :carrier
  has_one :freigth, foreign_key: "origin_city"
  has_one :freigth, foreign_key: "destination_city"
end

app/models/freight.rb
class Freight < ActiveRecord::Base
  attr_accessible :carrier_id, :origin_city_id, :destination_city_id, :start_weight, :end_weight, :value
  belongs_to :carrier
  belongs_to :destination_city, :class_name => 'City'
  belongs_to :origin_city, :class_name => 'City'

  validates  :carrier_id, :origin_city_id, :destination_city_id, :start_weight, :end_weight, :value, :presence => true

  scope :search_by_origin_city, lambda{ |origin_city, weight|
    where(origin_city_id: origin_city).
    where('((? >= start_weight AND ? <= end_weight) OR ? = -1) ', weight, weight, weight)
  }
  scope :search_by_destination_city, lambda{ |destination_city, weight|
    where(destination_city_id: destination_city).
    where('((? >= start_weight AND ? <= end_weight) OR ? = -1)', weight, weight, weight)
  }
  scope :search_all, lambda{ |origin_city, detination_city, weight|
    where(origin_city_id: origin_city).where(destination_city_id: detination_city).
    where('((? >= start_weight AND ? <= end_weight) OR ? = -1)', weight, weight, weight)
  }
  scope :search_table, lambda{ |weight|
    where('((? >= start_weight AND ? <= end_weight) OR ? = -1)', weight, weight, weight)
  }

  def self.search_type(origin_city, detination_city, weight)
    if weight.blank?
      weight = -1
    end

    case
    when origin_city.present? && detination_city.blank?
      result = Freight.search_by_origin_city(origin_city, weight)
    when detination_city.present? && origin_city.blank?
      result = Freight.search_by_destination_city(detination_city, weight)
    when origin_city.present? && detination_city.present?
      result = Freight.search_all(origin_city, detination_city, weight)
    else
      result = Freight.search_table(weight)
    end

    return result
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/carriers_controller.rb
class CarriersController < ApplicationController

  #menu_item :carriers

  def index
    @carriers = Carrier.all
  end

  def new
    @carrier = Carrier.new
  end

  def edit
    @carrier = Carrier.find(params[:id])
  end

  def create
    @carrier = Carrier.new(params[:carrier])
    if @carrier.save
      flash[:notice] = 'Transportadora cadastrada'
      redirect_to new_carrier_path
    else
      render :action => 'new'
    end
  end

  def update
    @carrier = Carrier.find(params[:id])
    if @carrier.update_attributes(params[:carrier])
      flash[:notice] = 'Transportadora alterada'
      redirect_to carriers_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @carrier = Carrier.find(params[:id])
    @carrier.destroy
    redirect_to carriers_path
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
  end
end

app/controllers/freights_controller.rb
class FreightsController < ApplicationController

  def index
    @freights = Freight.all
  end

  def new
    @freight = Freight.new
  end

  def edit
    @freight = Freight.find(params[:id])
  end

  def create
    @freight = Freight.new(params[:freight])
    if @freight.save
      flash[:notice] = 'Frete cadastrado'
      redirect_to new_freight_path
    else
      render :action => 'new'
    end
  end

  def update
    @freight = Freight.find(params[:id])
    if @freight.update_attributes(params[:freight])
      flash[:notice] = 'Frete alterado'
      redirect_to freights_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @freight = Freight.find(params[:id])
    @freight.destroy
    redirect_to freights_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end

  def result
    @data = params[:data]
    @freights = Freight.search_type(@data[:origin_city],@data[:destination_city],@data[:weight]).paginate(:page => params[:page], per_page: 3)
  end

  def more
    @freight = Freight.find(params[:id])
    @freights = Freight.where("carrier_id = ?", @freight.carrier_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_messages
    flash.collect do |key, msg|
      content_tag :p, msg, id: key, class: "flash_message"
    end.join.html_safe
  end

  def error_messages_for(resource)
    render partial: "shared/error_messages", locals: { resource: resource }
  end

  def link_to_new(model, url, html_options = {})
    link_to t("Novo", model: model.model_name.human), url, class: "button"
  end

  def link_to_edit(url, html_options = {})
    html_options.reverse_merge!(:class => "button")
    link_to t("Editar"), url, html_options
  end

  def link_to_destroy(url, html_options = {})
    html_options.reverse_merge!(:confirm => 'Are you sure?', :method => :delete, :class => "button")
    link_to t("Deletar"), url, html_options
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/carriers/_form.html.haml
= form_for [@carrier] do |f|
  = error_messages_for @carrier
  %p
    = f.text_field(:name, placeholder: "Nome")
  %p
    = f.text_field(:address, placeholder: "Endereço")
  %p
    = f.select :city_id, City.all.collect {|c| [ c.name, c.id ]}, prompt: '-- selecione --'
  %p
    = f.text_field(:zip_code, placeholder: "CEP")
  %p
    = f.text_field(:site, placeholder: "Site")
  %p
    = f.text_field(:phone, placeholder: "Telefone")
  %p
    = f.text_field(:e_mail, placeholder: "E-Mail")

  %hr(class="thick")

  %p
    = f.submit('Salvar',:class => "button")
    = link_to 'Cancelar', carriers_path, class: "button"

app/views/carriers/edit.html.haml
.show
  %h2
    Editar transportadora
  = render 'form'

app/views/carriers/index.html.haml
#carrier_index
  .show
    %h2
      Transportadoras
    %table(class="table")
      - @carriers.each do |carrier|
        = content_tag_for :tr, carrier, :class => cycle(:odd, :even) do
          %td.content
            .right
            = "#{carrier.name} (#{carrier.e_mail})"
            .right
              = link_to_edit [:edit, carrier]
              = link_to_destroy [carrier]

    %hr
    = link_to('Nova transportadora', new_carrier_path, class: "button")

app/views/carriers/new.html.haml
.show
  %h2
    Nova transportadora
  = render 'form'

app/views/freights/_form.html.haml
= form_for(@freight) do |f|
  = error_messages_for @freight
  %p
    = f.select :carrier_id, Carrier.all.collect {|c| [ c.name, c.id ]}, prompt: '-- selecione --'
  %p
    = f.select :origin_city_id, City.all.collect {|c| [ c.name, c.id ]}, prompt: '-- selecione --'
  %p
    = f.select :destination_city_id, City.all.collect {|c| [ c.name, c.id ]}, prompt: '-- selecione --'
  %p
    = f.text_field(:start_weight, placeholder: "Peso inicio")
  %p
    = f.text_field(:end_weight, placeholder: "Peso final")
  %p
    = f.text_field(:value, placeholder: "Valor")

  %hr

  %p
    = f.submit('Salvar',:class => "button")
    = link_to("Cancelar", freights_path,class: "button")

app/views/freights/edit.html.haml
.show
  %h2
    Editar frete
  = render 'form'

app/views/freights/index.html.haml
#freight_index
  .show
    %h2
      Fretes
    %table(class="table")
      - @freights.each do |freight|
        - if @freights.present?
          = content_tag_for :tr, freight, :class => cycle(:odd, :even) do
            %td.content
              .description.left
                = "#{freight.carrier.name}"
                %br
                = "Cidades: #{freight.origin_city.name} X #{freight.destination_city.name}"
                %br
                = "Peso inicial: #{freight.start_weight}Kg  X Peso final: #{freight.end_weight}Kg"
              .options
                = link_to_edit [:edit, freight]
              .options
                = link_to_destroy [freight]

    %hr
    = link_to('Novo frete', new_freight_path, class: "button")

app/views/freights/new.html.haml
.show
  %h2
    Novo frete
  = render 'form'

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title Frete
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Nunito'
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Fredoka+One'
  %body
    .top_bar
      .logo
        %h1 Frete fácil
    .menu
      .link_bar
        = link_to('Home', root_path, class: "link")
        = link_to('Transportadora', carriers_path, class: "link")
        = link_to('Frete', freights_path, class: "link")
    .show
      = flash_messages
    = yield

app/views/pages/index.html.haml
#page_index
  = form_for :data, url: page_result_path do |f|
    .show
      .search
        = f.label(:origin_city, "Cidade de origem   :")
        = f.select :origin_city, City.all.collect {|c| [ c.name, c.id ]}, prompt: '-- selecione --'
        %br
        = f.label(:destination_city, "Cidade de destino:")
        = f.select :destination_city, City.all.collect {|c| [ c.name, c.id ]}, prompt: '-- selecione --'
        %br
        = f.label(:weight, "Peso:")
        = f.text_field(:weight)
        = f.submit('Buscar',:class => "button")

app/views/pages/more.html.haml
#page_more
  .show
    .image
      = image_tag("http://www.showeb.com.br/imagens/transportadoras.jpg", :border => 0, :width => 300, :height =>300)
    .data
      %h1
        = @freight.carrier.name
      %br
      %h3
        = @freight.carrier.address
      %h3
        = @freight.carrier.city.name
      %h3
        = @freight.carrier.zip_code
      %h3
        = @freight.carrier.phone
      %h3
        = @freight.carrier.e_mail
      %h3
        = @freight.carrier.site
    .down
      .values
        %h1 Peso / Valor
        %table
          %thead
            %tr
              %th Peso (KG)
              %th Valor (R$)
          %tbody
            = content_tag_for :tr, @freights do |freight|
              %td
                = freight.start_weight
                a
                = freight.end_weight
              %td
                = number_to_currency(freight.value, unit: "", separator: ",", delimiter: ".")
      .location
        %h1 Localização (Maps)
        = image_tag("http://www.wmonline.com.br/files/Image/artigos/google-maps-empresa/maps-google-pontos.gif", :border => 0, :width => 300, :height =>300)

app/views/pages/result.html.haml
#page_result
  .show
    %h1
      Resultados encontrados
    .result
      - if @freights.present?
        .paginate
          = will_paginate @freights, :params=>{:data=>@data}
        %table(class="table_search")
          - @freights.each do |freight|
            = content_tag_for :tr, freight, class: cycle('odd', 'even') do
              %td
                .table_search_data.left
                  %h2
                    = freight.carrier.name
                  %br
                  Endereço:
                  = freight.carrier.address
                  %br
                  Cidade:
                  - if freight.carrier.city.present?
                    = freight.carrier.city.name
                  CEP:
                  = freight.carrier.zip_code
                  Fone:
                  = freight.carrier.phone
                  %br
                  Site:
                  = freight.carrier.site
                  E-mail:
                  = freight.carrier.e_mail
                .table_search_value.left
                  %h2 Valor
                  %h2
                    = number_to_currency(freight.value, :unit => "R$ ", :separator => ",", :delimiter => ".")
                  = link_to "Mais", freight_profile_path(freight.id), class: "button"
        .paginate
          = will_paginate @freights, :params=>{:data=>@data}

app/views/shared/_error_messages.html.haml
.content_
  - if resource.errors.any?
    %div(id="error_explanation")
      %h2
        = t "error_message_header", :count => resource.errors.count, :model => resource.class.model_name.human
      %ul
        - resource.errors.full_messages.each do |msg|
          %li
            = msg